version: '3'
networks:
  him:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  himcore:
    container_name: himcore
    image: jabahum/himcore:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-dev"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-dev"
      NODE_ENV: "production"
    ports:
      - "8081:8081"
      - "6000:5000"
      - "6001:5001"
    networks:
      - him
    healthcheck:
     test: "curl -sS http://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  himconsole:
    container_name: himconsole
    image: jabahum/himconsole:latest
    restart: unless-stopped
    networks:
      - him
    ports:
      - "9090:80"
    volumes:
      - "../app/config/default.json:/usr/share/nginx/html/config/default.json"
    healthcheck:
     test: "curl -sS http://himconsole || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

volumes:
  mongo-data:
